#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9001/eureka/
#端口
server: 
  port: 8999
  tomcat: 
    uri-encoding: UTF-8
spring:
#  application:
#    name: client
  thymeleaf:
      prefix: classpath:/templates
      encoding: UTF-8
  #缓存
      cache: false
#表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
#在这里配置静态资源路径，前面说了这里的配置是覆盖默认配置，
#所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径，
#在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径，
#其他的使用classpath指的是系统环境变量
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:${imgPath}

#邮箱
  mail:
#  smtp.163.com
    host: smtp.qq.com
    username: 287656156@qq.com
    password: capvszpolemibgdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
feign:
  hystrix:
#  开启熔断机制，默认是开启的
    enabled: true
  httpclient:
    enabled: true
#    设置超时时间，防止首次调用出现服务宕机bug
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
# 日志级别
error: true
logging:
    file: client.log
    level: org.client.com:debug

#分页每页默认条数设置
page:
  pageSize: 15
  
#全局上传下载读取img路径设置
imgPath: D:\\work\\
#全局图片格式-多个用,(英文)隔开
imgType: jpg,png

#全局上传下载读取文件路径设置
filesPath: D:\\file\\
#全局文件格式-多个用,(英文)隔开
filesType: xlsx